---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Demo homepage"
subtitle: "Homer"
logo: "assets/logo.png"
# icon: "fas fa-skull-crossbones" Optional icon

# Optional message
# 
message:
  # url: https://....
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !" 
  content: "This is a dummy homepage demo. Find more information on github.com/bastienwirtz/homer"

# Optional navbar
links:
  - name: "ansible"
    icon: "fab fa-github"
    url: "https://github.com/xxxxx/ansible/"
    target: '_blank' # optionnal html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://wiki.xxxxxx.com/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "DevOps"
    icon: "fas fa-code-branch"
    items:
      - name: "Jenkins"
        logo: "assets/tools/jenkins.png"
        subtitle: "Continuous integration server"
        tag: "CI"
        url: "https://jenkins.io/"
        target: '_blank' # optionnal html a tag target attribute
      - name: "RabbitMQ Management"
        logo: "assets/tools/rabbitmq.png"
        subtitle: "Manage & monitor RabbitMQ server"
        tag: "haproxy"
        # Optional tagstyle
        # Same styling options as the optional message.
        tagstyle: "is-success"
        url: "https://www.rabbitmq.com/"
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "M/Monit"
        logo: "assets/tools/monit.png"
        subtitle: "Monitor & manage all monit enabled hosts"
        tag: "monit"
        url: "https://mmonit.com/monit/"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.com/"
      - name: "Kibana"
        logo: "assets/tools/elastic.png"
        subtitle: "Explore & visualize logs"
        tag: "elk"
        url: "https://www.elastic.co/products/kibana"
      - name: "Website monitoring"
        logo: "assets/tools/pingdom.png"
        subtitle: "Pingdom public reports overview"
        tag: "CI"
        url: "https://www.pingdom.com/"
