---
version: "2"
services:
  homer:
    #image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    build: https://github.com/FriendlyNGeeks/homer
    container_name: homer
    volumes:
      - /your/local/assets/:/www/assets
    ports:
      - 1000:8080
    #environment:
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped
